name: ucnz
channels:
  - conda-forge
  - defaults
dependencies:
  - anaflow=1.0.1=py_0
  - anyio=3.5.0=py37haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - attrs=22.1.0=py37haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - branca=0.4.2=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.2.2=h56e8100_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py37h2bbff1b_3
  - colorama=0.4.6=py37haa95532_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37haa95532_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - geos=3.8.0=h33f27b4_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py37haa95532_0
  - importlib-metadata=4.11.3=py37haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipyleaflet=0.14.0=pyhd8ed1ab_1
  - ipython=7.31.1=py37haa95532_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.7.2=pyhd8ed1ab_0
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.1.2=py37haa95532_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=4.17.3=py37haa95532_0
  - jupyter_client=7.4.9=py37haa95532_0
  - jupyter_core=4.11.2=py37haa95532_0
  - jupyter_server=1.23.4=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.4=py37hd77b12b_0
  - krb5=1.20.1=h5b6d351_1
  - lerc=3.0=hd77b12b_0
  - libblas=3.8.0=20_mkl
  - libcblas=3.8.0=20_mkl
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.5.0=h86230a5_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_2
  - liblapack=3.8.0=20_mkl
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=hb652d5d_1
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=hcd4344a_2
  - libtiff=4.4.0=h8a3f274_2
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py37h2bbff1b_0
  - matplotlib=3.3.3=py37h03978a9_0
  - matplotlib-base=3.3.3=py37h3379fd5_0
  - matplotlib-inline=0.1.6=py37haa95532_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h196d8e1_0
  - mpmath=1.2.1=py37haa95532_0
  - nbclassic=0.5.2=py37haa95532_0
  - nbclient=0.5.13=py37haa95532_0
  - nbconvert=6.4.4=py37haa95532_0
  - nbformat=5.7.0=py37haa95532_0
  - nest-asyncio=1.5.6=py37haa95532_0
  - notebook=6.5.2=py37haa95532_0
  - notebook-shim=0.2.2=py37haa95532_0
  - numpy=1.19.5=py37h4c2b6ed_3
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=22.0=py37haa95532_0
  - pandas=1.2.0=py37hf11a4ad_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=h0ff8eda_0
  - pentapy=1.1.0=py37h4ab8f01_2
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py37hdc2b20a_1
  - pip=22.3.1=py37haa95532_0
  - pkgutil-resolve-name=1.3.10=py37haa95532_0
  - ply=3.11=py37_0
  - proj=8.1.0=h1cfcee9_1
  - prometheus_client=0.14.1=py37haa95532_0
  - prompt-toolkit=3.0.36=py37haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py37haa95532_0
  - pyproj=3.1.0=py37h1e4c353_4
  - pyqt=5.15.7=py37hd77b12b_0
  - pyqt5-sip=12.11.0=py37hd77b12b_0
  - pyrsistent=0.18.0=py37h196d8e1_0
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37haa95532_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.7=py37haa95532_0
  - pywin32=305=py37h2bbff1b_0
  - pywinpty=2.0.10=py37h5da7b33_0
  - pyzmq=23.2.0=py37hd77b12b_0
  - qt-main=5.15.2=h6072711_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtwebkit=5.212=h2bbfb41_5
  - scikit-learn=0.22.1=py37h7208079_1
  - scipy=1.6.0=py37h14eb087_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py37haa95532_0
  - shapely=1.8.4=py37h9064783_0
  - sip=6.6.2=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py37haa95532_1
  - soupsieve=2.3.2.post1=py37haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.7.1=py37haa95532_0
  - terminado=0.17.1=py37haa95532_0
  - testpath=0.6.0=py37haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py37h2bbff1b_0
  - traitlets=5.7.1=py37haa95532_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing-extensions=4.4.0=py37haa95532_0
  - typing_extensions=4.4.0=py37haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37haa95532_4
  - wheel=0.38.4=py37haa95532_0
  - widgetsnbextension=3.6.6=pyhd8ed1ab_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - xlrd=1.2.0=py37_0
  - xz=5.4.6=h8cc25b3_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py37haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
